import secrets
from uuid import UUID

from sqlalchemy.orm import Session

from backend.models.db_models import Workspace


# 32 random bytes -> 43 URL-safe characters (fits String(64)).
GUEST_ID_BYTES = 32


def generate_guest_id() -> str:
    """
    Create an unguessable guest identifier.

    Guest IDs must ALWAYS be generated by the server. A guest ID acts
    like a bearer token: whoever holds it can access that guest's
    workspaces, so it must never be chosen by the client.
    """
    return secrets.token_urlsafe(GUEST_ID_BYTES)


def guest_exists(
    db: Session,
    guest_id: str,
) -> bool:
    """
    Check whether a guest ID was issued by this server
    (i.e. at least one workspace belongs to it).
    """
    return (
        db.query(Workspace.id)
        .filter(Workspace.guest_id == guest_id)
        .first()
        is not None
    )


def create_workspace(
    db: Session,
    name: str,
    user_id: UUID | None = None,
    guest_id: str | None = None,
) -> Workspace:
    """
    Create a workspace owned by exactly one identity:
    a registered user (user_id) OR a guest (guest_id).
    """
    if (user_id is None) == (guest_id is None):
        raise ValueError(
            "A workspace must have exactly one owner: "
            "provide either user_id or guest_id"
        )

    workspace = Workspace(
        name=name,
        user_id=user_id,
        guest_id=guest_id,
    )

    db.add(workspace)
    db.commit()
    db.refresh(workspace)

    return workspace


def get_workspace(
    db: Session,
    workspace_id,
) -> Workspace | None:
    return (
        db.query(Workspace)
        .filter(Workspace.id == workspace_id)
        .first()
    )


def list_workspaces(
    db: Session,
) -> list[Workspace]:
    return (
        db.query(Workspace)
        .order_by(Workspace.created_at.desc())
        .all()
    )


def list_user_workspaces(
    db: Session,
    user_id: UUID,
) -> list[Workspace]:
    return (
        db.query(Workspace)
        .filter(Workspace.user_id == user_id)
        .order_by(Workspace.created_at.desc())
        .all()
    )


def list_guest_workspaces(
    db: Session,
    guest_id: str,
) -> list[Workspace]:
    return (
        db.query(Workspace)
        .filter(Workspace.guest_id == guest_id)
        .order_by(Workspace.created_at.desc())
        .all()
    )


def transfer_guest_workspaces_to_user(
    db: Session,
    guest_id: str,
    user_id: UUID,
) -> int:
    """
    Guest -> account conversion (Phase 3.10).

    Moves every workspace owned by the guest to the user in a single
    UPDATE, so the "exactly one owner" rule is never violated.
    Returns the number of workspaces transferred.
    """
    transferred = (
        db.query(Workspace)
        .filter(Workspace.guest_id == guest_id)
        .update(
            {
                Workspace.user_id: user_id,
                Workspace.guest_id: None,
            },
            synchronize_session=False,
        )
    )

    db.commit()

    return transferred
